
[prometheus]
http_addr = "0.0.0.0:3000"

[system_monitor]
enabled = true
scrape_period = "1s"

[process_monitor]
enabled = true
scrape_period = "1s"
processes = ["chrome", "gopls"]

[system_informer]
enabled = true
scrape_period = "1s"
